apiVersion: v1
kind: Namespace
metadata:
  name: orbeon
  labels:
    app: orbeon
    tier: backend
    env: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    app: minio
    tier: backend
    env: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app: grafana
    tier: observability
    env: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: proxy
  labels:
    app: nginx
    tier: edge
    env: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    app: authelia
    tier: identity
    env: prod
