apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-basic-access
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-monitoring-basic-access
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring
roleRef:
  kind: Role
  name: monitoring-basic-access
  apiGroup: rbac.authorization.k8s.io
