apiVersion: v1
kind: PersistentVolume
metadata:
  name: orbeon-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /export/k3s-data/orbeon
    server: 192.168.1.100
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orbeon-pvc
  namespace: orbeon
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi 
  volumeName: orbeon-pv
  storageClassName: ""